### ISSUE TITLE
FileDevice does not work (for raw printing)

### ISSUE THREAD

**Issue by mgoppold** [apple/cups#5117] opened 2017-09-20 13:01 UTC
in 

cups-1.7.5-8.3.1.x86_64 from openSUSE Leap 42.3 and 
cups-2.2.3-212.1.x86_64 from Printing System Development Project (openSUSE_Leap_42.3)

the FileDevice directive is broken. 

```
# grep FileDevice /etc/cups/cups-files.conf
FileDevice Yes
```

Setup Printer:
```
# lpadmin -p PTEST-0100 -v file:///tmp/0100.prn -E
```

Testcase:
```
# lp -d PTEST-0100 /etc/hosts
# ls -l /tmp/0100.prn 
ls: cannot access '/tmp/0100.prn': No such file or directory
```

**Comment by jsmeix** [comment] 2017-09-21 07:23
FileDevice do not and never did work for raw queue.
I gess that is somewhere documented
but currently I don't rememebre where.
You need a filter (i.e. a PPD) in between:
<pre>
# rpm -q cups
cups-2.2.3-210.1.x86_64

# grep FileDevice /etc/cups/cups-files.conf
FileDevice Yes

# lpadmin -p PTEST-0100 -v file:///tmp/0100.prn -P /usr/share/cups/model/Postscript.ppd.gz -E

# lp -d PTEST-0100 /etc/hosts
request id is PTEST-0100-8440 (1 file(s))

# file /tmp/0100.prn
/tmp/0100.prn: PostScript document text conforming DSC level 3.0, Level 2
</pre>

**Comment by mgoppold** [comment] 2017-09-21 10:04
before version 1.6.0 i have use it for debug reasons almost daily. I have just compile and test against master and found that your comment is correct.

Setup the printer with a PPD it does what i want (with filters applied) but with

`
lp -d PTEST-0100 -o raw /etc/hosts
`

nothing is written to the destination file.

Yesterday I have tested cups154 from OBS 42.3 and the destination file is written and shows no diff againts the source.

**Comment by mgoppold** [comment] 2017-09-21 11:57
```
opensuse423devel64:~ # rpm -q cups154
cups154-1.5.4-3.2.x86_64
opensuse423devel64:~ # lpadmin -x PTEST-0100
opensuse423devel64:~ # lpadmin -p PTEST-0100 -v file:///tmp/0100.prn -E
opensuse423devel64:~ # rm -f /tmp/0100.prn
opensuse423devel64:~ # lp -d PTEST-0100 /etc/hosts
request id is PTEST-0100-15 (1 file(s))
opensuse423devel64:~ # ls -l /tmp/0100.prn
-rw------- 1 root root 1260 Sep 21 13:56 /tmp/0100.prn
opensuse423devel64:~ # diff /etc/hosts /tmp/0100.prn; echo $?
0
```

**Comment by michaelrsweet** [comment] 2017-09-22 02:59
Stock CUPS has never supported raw queues with file: device URIs. I've committed a change to the cups-files.conf man page to re-document this and other limitations - file: devices are for testing/development only, never for production usage.

**Closed by michaelrsweet** 2017-09-22 02:59 UTC
Labels: P2 - Low

**Comment by jsmeix** [comment] 2017-09-22 08:30
@michaelrsweet 
I think
https://github.com/apple/cups/issues/5117#issuecomment-331337279
needs a correction:
I think stock CUPS has supported raw queues with file: device URIs
more or less by accident because at some time stock CUPS used
the 'gziptoany' filter in any case i.e. also for 'raw' printing
at least I could reproduce that in CUPS 1.5.4, cf.
https://github.com/apple/cups/issues/4782#issuecomment-197693787

@mgoppold 
see my /usr/lib/cups/backend/tofile that works in any case in
https://github.com/apple/cups/issues/4782#issue-141477390
and in general see
https://en.opensuse.org/SDB:Using_Your_Own_Backends_to_Print_with_CUPS
where I added right now the section
"A backend that sends its input into a file for debugging"

**Comment by jsmeix** [comment] 2017-09-22 08:41
@michaelrsweet FYI:
since CUPS 1.4 we (i.e. SUSE) should provide a
well upstream-compliant CUPS with only few patches.
For exaxt data you can inspect our CUPS package sources at
https://build.opensuse.org/package/show/Printing/cups
Therein see in particular in the RPM changes file
https://build.opensuse.org/package/view_file/Printing/cups/cups.changes?expand=1
that contains in particular this entry:
<pre>
Wed Jan 27 14:43:37 CET 2010 - jsmeix@suse.de

- CUPS 1.3 -> 1.4 version upgrade and major cleanup:
  For the CUPS upstream changes see the CHANGES.txt file.
  Such a major version upgrade is the perfect chance
  to drop almost all our own patches to enforce a
  reset to almost 100% compliance with upstream.
  Here our openSUSE CUPS versions and their number of patches
  (i.e. the "Patch" entries in the cups.spec files):
    CUPS version 1.2.12 in openSUSE 10.3: 37
    CUPS version 1.3.7  in openSUSE 11.0: 29
    CUPS version 1.3.9  in openSUSE 11.1: 26
    CUPS version 1.3.11 in openSUSE 11.2: 17
  Of course this includes patches with backported bug fixes
  via our maintenance but nevertheless there were really
  too much openSUSE specific patches.
  Therefore I would like to provide CUPS 1.4 "as is" to the
  furthest possible extent (there are still 6 patches left).
  Then let's see if we get bug reports because of this.
  I did such a reset to 100% compliance with upstream
  already in the past for sane-backends and guess what:
  I got no single bug report at all because of this.
  I guess what they do at upstream is actually not so bad ;-)
</pre>

**Comment by mgoppold** [comment] 2017-09-22 15:20
Thanks for the hints and explanations. 

I will modify my testsuits to remove the File-Uris now.
