### ISSUE TITLE
2.3b6 doesn't build (main.c:158:7: error: too few arguments to function 'usage')

### ISSUE THREAD

**Issue by OdyX** [apple/cups#5453] opened 2018-12-10 08:35 UTC
https://github.com/apple/cups/blob/v2.3b6/scheduler/main.c#L158 uses `usage()`:
```C
for (i = 1; i < argc; i ++)
  {
    if (!strcmp(argv[i], "--help"))
      usage();
else if (argv[i][0] == '-')
```
… but it is defined at https://github.com/apple/cups/blob/v2.3b6/scheduler/main.c#L2129 as:
```C
/*
 * 'usage()' - Show scheduler usage.
 */

static void
usage(int status)			/* O - Exit status */
{
FILE	*fp = status ? stderr : stdout; /* Output file */
```

The fix is straightforward:
```patch
--- a/scheduler/main.c
+++ b/scheduler/main.c
@@ -155,7 +155,7 @@ main(int  argc,                             /* I - Number of command-line args */
   for (i = 1; i < argc; i ++)
   {
     if (!strcmp(argv[i], "--help"))
-      usage();
+      usage(0);
     else if (argv[i][0] == '-')
     {
       for (opt = argv[i] + 1; *opt != '\0'; opt ++)
```

**Comment by michaelrsweet** [comment] 2018-12-10 12:00
Dupe of issue #5451

**Closed by michaelrsweet** 2018-12-10 12:00 UTC
