### ISSUE TITLE
4 second delay before printing

### ISSUE THREAD

**Issue by bob59147** [apple/cups#5377] opened 2018-08-22 09:14 UTC
Hello, we have a problem with cups, when we want to print there is a delay of 4 seconds before printing, this delay does not exist under windows.

We used a rapsberry pi (rapsbian 9.4), the version of cups is 2.2.1 and we use the drivers for a zebra printer "Zebra EPL2 Label Printer"

I would thank you if you could try to help us with this problem,

Can you tell me what additional information I should provide you so that you can help me?

Regards

[cups_ppd.txt](https://github.com/apple/cups/files/2309625/cups_ppd.txt)

**Comment by michaelrsweet** [comment] 2018-08-22 12:08
Dupe of issue #5256.

**Closed by michaelrsweet** 2018-08-22 12:08 UTC
