### ISSUE TITLE
Delayed Print Action

### ISSUE THREAD

**Issue by Arvish12** [apple/cups#5251] opened 2018-02-19 21:29 UTC
Hello out there.  Help required.

I am using a  Star Micronics thermal printer TSP654 (STR_T-001) via USB on Ubuntu 16.04.
I have built the driver as instructed from the vendor.  When printing a small text file, printing happens immediately with no error.  As soon as the text file is larger OR I choose to print multiple copies, the printing process seems to slow down dramatically.

The CUPS erro_log shows countless entries as follows :
D [19/Feb/2018:23:06:27 +0200] [Job 38] Read 9 bytes of back-channel data...
D [19/Feb/2018:23:06:27 +0200] [Job 38] Read 9 bytes of back-channel data...
D [19/Feb/2018:23:06:27 +0200] [Job 38] Read 9 bytes of back-channel data...
D [19/Feb/2018:23:06:27 +0200] [Job 38] Read 9 bytes of back-channel data...
D [19/Feb/2018:23:06:27 +0200] [Job 38] Read 9 bytes of back-channel data...
D [19/Feb/2018:23:06:27 +0200] [Job 38] Read 9 bytes of back-channel data...
D [19/Feb/2018:23:06:27 +0200] [Job 38] Read 9 bytes of back-channel data...
D [19/Feb/2018:23:06:27 +0200] [Job 38] Read 9 bytes of back-channel data...
D [19/Feb/2018:23:06:27 +0200] [Job 38] Read 9 bytes of back-channel data...
D [19/Feb/2018:23:06:27 +0200] [Job 38] Read 9 bytes of back-channel data...

And after some time, sometimes 2-3 minutes, sometimes more, the document eventually prints.  What on earth could be causing CUPS to only read 9 bytes of data at a time ???

**Comment by michaelrsweet** [comment] 2018-02-20 14:59
Doing a little research, the following should do the trick:

    0x0519 unidir

I've pushed this change to master, pending confirmation that the change fixes things for you:

[master a468069a2] Use unidirectional mode for Star Micronics printers (Issue #5251)

**Comment by Arvish12** [comment] 2018-02-20 19:32
Thanks so much for your replies. 

I have done as instructed, inserted '0x0519 unidir' into a file in  /usr/share//cups/usb/, and the behavior of the printer has changed.  If I now print 3 copies of an extremely small text file, it works perfectly.  However, as soon as I increase the size of the text file and print multiple copies, a different issue seems to occur.  The printer jams, and the job seems to disappear.  Please see error log below : 

I [20/Feb/2018:21:21:06 +0200] Saving subscriptions.conf...
D [20/Feb/2018:21:21:06 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Dirty files"
I [20/Feb/2018:21:21:06 +0200] Expiring subscriptions...
D [20/Feb/2018:21:21:06 +0200] Report: clients=10
D [20/Feb/2018:21:21:06 +0200] Report: jobs=5
D [20/Feb/2018:21:21:06 +0200] Report: jobs-active=0
D [20/Feb/2018:21:21:06 +0200] Report: printers=1
D [20/Feb/2018:21:21:06 +0200] Report: stringpool-string-count=18775
D [20/Feb/2018:21:21:06 +0200] Report: stringpool-alloc-bytes=11720
D [20/Feb/2018:21:21:06 +0200] Report: stringpool-total-bytes=419024

Further advice would be greatly appreciated.

**Comment by michaelrsweet** [comment] 2018-02-20 19:43
Sigh, that sounds like the printer doesn't actually implement the USB printer class properly - as soon as it falls behind it sounds like it starts dropping data.

Not sure what can be done to resolve this, but I'd try to get the manufacturer involved...

**Comment by Arvish12** [comment] 2018-02-20 20:07
Ok, thanks for the help.  I will have to keep at it.

Moving forward though, do you have any recommendations for thermal printers that work well with the CUPS system ?

**Comment by michaelrsweet** [comment] 2018-02-20 20:21
The Zebra printers I've worked most recently with have all been solid. In the (somewhat distant) past I used Dymo printers for printing hundreds of smaller labels on a daily basis, however none of the models I used back then are still sold today... Both are supported by the bundled CUPS label printer driver.

**Comment by Arvish12** [comment] 2018-02-20 20:47
Ok great, will look into those.  Whats strange for me is that I have used this exact same Star printer on Ubuntu 14 running CUPS 1.5.2 and it is working flawlessly up till this day.  I was wrong to assume the same with the most updated software.  Anyways, thanks once again...

**Comment by michaelrsweet** [comment] 2018-02-20 20:51
The backend has probably changed from using the kernel "lp" module to the libusb-based backend and lower-level kernel USB driver. Plus you are using a newer Linux kernel - probably what worked before due to a timing or compatibility hack no longer works... :/

**Comment by jsmeix** [comment] 2018-02-21 08:26
@Arvish12 
probably not a solution but perhaps the following might help you
to do some further attempts how you could make that particular USB device
(I won't call it a real USB printer ;-) accept the data more reliably:

1)
Have a look at
https://en.opensuse.org/SDB:Using_Your_Own_Backends_to_Print_with_CUPS
how you might experiment with a selfmade backend
to send the data to that particular USB device.
When you do things like `cat - >/dev/usb/lp0`
to send the data to that USB device the traditional way
via the 'usblp' kernel module might be used, have a look at
https://en.opensuse.org/SDB:Installing_a_Printer
regarding kernel modules for direct USB printer access
(the 'lp' kernel module is used for parallel port access).

2)
What kind of USB port is used at your computer?
Is it perhaps a USB 3 port (i.e. USB 3 hardware in the computer)?

At last for USB scanners there are known issues with the
data transfer if a USB 3 port is used at the computer,
cf. the "USB" section in
https://en.opensuse.org/SDB:Configuring_Scanners

Nowadays "xhci_hcd" kernel driver/module issues (a.k.a. "USB 3")
are the most often cause of issues like "Error during device I/O", cf.
http://lists.alioth.debian.org/pipermail/sane-devel/2016-November/034901.html
and follow the links therein.

Regarding how to get kernel related USB messages,
see the section "Do not overdo things" in
https://en.opensuse.org/SDB:How_to_Report_a_Printing_Issue
therein about "get usb-related kernel messages".

In particular see
http://lists.alioth.debian.org/pipermail/sane-devel/2015-December/034207.html
(excerpt):
<pre>
Regarding "USB 2.0 (black) and USB 3.0 (blue)":

Neither the color nor what the port is labeled on the computer
is reliable regarding what kernel driver is used for the port.

Only the "lsusb -t" output shows what kernel driver is used.

For example all USB ports on my testing machine have same dark color.
Also the "super speed" (USB 3) labeled ports are basically black.
Their exact color is "very dark" but not "100% black"
and neither blue (USB 3.0) nor teal blue (USB 3.1), cf.
https://en.wikipedia.org/wiki/USB#Colors

On my testing machine xhci_hcd is used for all USB ports
where I can connect devices (i.e. all external USB ports).
</pre>

If USB 3 (i.e. the xhci_hcd kernel driver) is the root cause,
the best way out is to use real USB 2 hardware (i.e. a USB port
at the computer where not xhci_hcd is used) or when there is
no such port to buy additional real USB 2 hardware and use that
to get problems with USB 3 out of sight, cf.
https://bugzilla.opensuse.org/show_bug.cgi?id=856794#c49

**Comment by michaelrsweet** [comment] 2018-03-08 16:55
OK, I'm going to close this bug as "fixed" as much as we can fix it on our end. Please let me know if there are other changes we can make to improve the performance of these printers...

**Closed by michaelrsweet** 2018-03-08 16:55 UTC
Labels: P2 - Low, Waiting on Review
