### ISSUE TITLE
cupsd crashed with SIGSEGV in create_local_bg_thread()

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5290] opened 2018-04-09 17:27 UTC
I got this bug report on Ubuntu, for CUPS 2.2.7:
https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1762476
The user told that the crash happened right after boot, visible by a pop-up of Ubuntu's automatic crash reporting system.
The system attached a stack trace to the Ubuntu bug report:
https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1762476/+attachment/5108208/+files/ThreadStacktrace.txt

**Comment by michaelrsweet** [comment] 2018-04-09 17:52
This is almost certainly a dupe of Issue #5258.

**Comment by tillkamppeter** [comment] 2018-04-09 19:16
Did the fix of Issue #5258 not get backported into 2.2.7? The original reporter has this problem in 2.2.7.

**Comment by michaelrsweet** [comment] 2018-04-09 19:28
It did, but after looking more closely it looks like it is crashing in another spot of the background thread... Reopening...

**Comment by michaelrsweet** [comment] 2018-04-09 19:32
[master 656c109a1] Fix another CUPS-Create-Local-Printer crash (Issue #5290)
[branch-2.2 f6d93318e] Fix another CUPS-Create-Local-Printer crash (Issue #5290)

**Closed by michaelrsweet** 2018-04-09 19:32 UTC
Labels: P4 - High

**Comment by tillkamppeter** [comment] 2018-04-09 19:38
Thank you very much for the quick fix, I will apply it to Ubuntu 18.04 LTS.
