### ISSUE TITLE
rpmbuild: Installed but unpackaged file found: cups_zh_CN.po

### ISSUE THREAD

**Issue by avlis** [apple/cups#5063] opened 2017-07-17 14:28 UTC
Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/rpmbuild/BUILDROOT/cups-2.2.4-0.x86_64
error: Installed (but unpackaged) file(s) found:
   /usr/share/locale/zh_CN/cups_zh_CN.po

RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/share/locale/zh_CN/cups_zh_CN.po

**Comment by michaelrsweet** [comment] 2017-07-17 22:02
Dupe of Issue #5043 and #5044.

**Comment by michaelrsweet** [comment] 2017-07-17 22:02
(and already fixed in the repo...)

**Closed by michaelrsweet** 2017-07-17 22:02 UTC
