### ISSUE TITLE
cups-driverd: CUPS issue #3185 reappears

### ISSUE THREAD

**Issue by debiantriage** [apple/cups#5219] opened 2018-01-10 19:53 UTC
We have a bug report in Debian - #886224
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886224

The thread is rather long so
https://lists.debian.org/debian-printing/2018/01/msg00047.html
and
https://lists.debian.org/debian-printing/2018/01/msg00050.html
are probably the posts to read

Regards,

Brian.

**Comment by michaelrsweet** [comment] 2018-01-10 20:02
Appears to be a regression caused by the fix for Issue #5170.

**Comment by debiantriage** [comment] 2018-01-10 20:25
Egad! That was a quick response. Thanks.

**Comment by michaelrsweet** [comment] 2018-01-11 15:39
@debiantriage OK, so going back through that bug report, it looks like this is actually a dupe of Issue #5170, which fixes this problem by returning 1 from load_ppds when a loop is seen instead of 0.

It looks like this is already fixed... :)

**Closed by michaelrsweet** 2018-01-11 15:39 UTC
Labels: P5 - Critical, Regression
