### ISSUE TITLE
Unable to print multiple files to a local printer

### ISSUE THREAD

**Issue by Abhik1998** [apple/cups#5819] opened 2020-08-10 14:27 UTC
Hey!!
I wanted to print multiple files through my local printer using lp command `lp test1.pdf test2.pdf` but it is printing only the first file.
I am currently using cups version: 2.3.3
The print queue size appears to be correct (equivalent to that of multiple files) but in the location /var/spool/cups only a single file (test1.pdf) is present. Possibly, the lp command does not submit all the files or there is an issue with the CUPS itself.
Reference issue :[ OpenPrinting/cups-filters/#187](https://github.com/OpenPrinting/cups-filters/issues/187)

**Comment by motedon** [comment] 2020-08-12 06:32
I have the same issue. I'm also running cups 2.3.3 and I can't print more than 1 copy of a document. I have a HP Ink Tank wireless 415 printer. Even downgrading to 2.3.1 doesn't solve the issue.

**Comment by jschwender** [comment] 2020-08-20 13:01
could be a duplicate of #5796, is this on Linux using cups-filters?

**Comment by Abhik1998** [comment] 2020-08-20 14:01
Not exactly @jschwender, in case of multiple copies of the same file it works good but not multiple files.
Yes, it's on Linux using cups-filters.

**Comment by yash-sudo** [comment] 2020-11-11 16:02
Its working fine for me on Ubuntu20.04 with CUPS 2.3.3.  
lp file1 file2 is printing both the files.

**Comment by surajkulriya** [comment] 2021-01-15 05:49
hello @yash-sudo 
can you please show me the ppd file you are using.
Thanks

**Comment by michaelrsweet** [comment] 2021-03-12 15:14
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.

**Closed by michaelrsweet** 2021-03-12 15:14 UTC
