### ISSUE TITLE
 CUPS control files missing job-name's

### ISSUE THREAD

**Issue by Srikanthpandrahalli** [apple/cups#4806] opened 2016-04-18 11:08 UTC
When a single LPR command submits multiple files from CUPS
client to  CUPS print server the control file (c0000x-xxx) that
creates in /var/spool/cups dir  does not contain all the file
names (job-name). But, a data file (d0000x-xxx) for each file is created.

Sample LPR command
# lpr -P blane /tmp/sample1.txt /tmp/sample2.txt /tmp/sample3.txt

Checking contents of /var/spool/cups/c00055 CUPS control file only one file
(job-name) sample1.txt exist. Missing are sample2.txt and sample3.txt

# cd /var/spool/cups

/var/spool/cups# cat c00055
G attributes-charset utf-8H attributes-natural-language enE printer-uri
"ipp://localhost:631/printers/blaneB job-originating-user-name rootB job-name
sample1.txt I document-format text/plain! copies

All data files were created.
/var/spool/cups# ls
c00055      d00055-001  d00055-002  d00055-003  tmp
/var/spool/cups#

**Comment by jsmeix** [comment] 2016-04-18 14:33
Looks like a duplicate of https://github.com/apple/cups/issues/4805
see in particular Michael Sweet's explanation https://github.com/apple/cups/issues/4805#issuecomment-211061981

I would not expect to much from the autogenerated job title.

I think if you need a particular job title, you must explicity
specify it in the command e.g. something like
<pre>
lp -d queue_name -t 'file1_file2_file3' file1 file2 file3
</pre>

**Comment by michaelrsweet** [comment] 2016-04-18 15:13
Not exact a dupe of issue #4805, but a similar cause.

CUPS supports multiple document jobs but does not support the IPP document object extension which would give you access to the names of individual documents in the job. And in particular the LPD protocol does not provide a way to name individual files in a job, just the overall name/title of the job.

**Closed by michaelrsweet** 2016-04-18 15:13 UTC

**Comment by Srikanthpandrahalli** [comment] 2016-04-19 05:47
Thanks for your response.

Srikanth
