### ISSUE TITLE
TLS packet with CUPS error

### ISSUE THREAD

**Issue by SiNGhKs** [apple/cups#5151] opened 2017-10-25 11:52 UTC
Hello,

@michaelrsweet i asked my question on lot of debian community forum but i don't receive response. Can you help me please ?

I recently installed my CUPS server on Debian 8. When i do manual print from Windows client with this command:

`lpr -S 15.21.225.11 -P Test_Print C:\Users\singh\Desktop\Test.txt`

I get this error:

   

>  Error: print server did not accept request. Job

 

In my CUPS logs I have:

> [25/Oct/2017:13:22:43 +0200] Unable to encrypt connection from 15.21.226.129 - An unexpected TLS packet was received.

> [25/Oct/2017:13:33:07 +0200] Unable to encrypt connection from 15.21.226.129 - An unexpected TLS packet was received.

     

I already activated TLS on my CUPS in cupsd.conf. The whole config file:

`LogLevel warn
        MaxLogSize 0

        ServerName cups
        #Encryption Always
        #Listen localhost:631
        Listen /var/run/cups/cups.sock
        Listen 15.21.225.11:631
        Listen 15.21.225.11:515
        SSLListen 0.0.0.0:632
        Browsing On
        BrowseLocalProtocols dnssd
        DefaultAuthType Basic
        WebInterface Yes
        <Location />
          Order allow,deny
          Allow all
        </Location>
        <Location /admin>
          Order allow,deny
          Allow all
        Encryption Required
        </Location>
        <Location /admin/conf>
          AuthType Default
          Require user @SYSTEM
          Order allow,deny
          Allow all
        </Location>
        <Policy default>
          JobPrivateAccess default
          JobPrivateValues default
          SubscriptionPrivateAccess default
          SubscriptionPrivateValues default
          <Limit Create-Job Print-Job Print-URI Validate-Job>
            Order deny,allow
           Encryption Required

          </Limit>
          <Limit Send-Document Send-URI Hold-Job Release-Job Restart-Job Purge-Jobs Set-Job-Attributes Create-Job-Subscription Renew-Subscription Cancel-Subscription Get-Notifications $
            Require user @OWNER @SYSTEM
            Order deny,allow
           Encryption Required
          </Limit>
          <Limit CUPS-Add-Modify-Printer CUPS-Delete-Printer CUPS-Add-Modify-Class CUPS-Delete-Class CUPS-Set-Default CUPS-Get-Devices>
            AuthType Default
            Require user @SYSTEM
            Order deny,allow
        Encryption Required
      </Limit>
      <Limit Pause-Printer Resume-Printer Enable-Printer Disable-Printer Pause-Printer-After-Current-Job Hold-New-Jobs Release-Held-New-Jobs Deactivate-Printer Activate-Printer Res$
        AuthType Default
        Require user @SYSTEM
        Order deny,allow
      </Limit>
      <Limit Cancel-Job CUPS-Authenticate-Job>
        Require user @OWNER @SYSTEM
        Order deny,allow
      </Limit>
      <Limit All>
        Order deny,allow
      </Limit>
    </Policy>
    <Policy authenticated>
      JobPrivateAccess default
      JobPrivateValues default
      SubscriptionPrivateAccess default
      SubscriptionPrivateValues default
      <Limit Create-Job Print-Job Print-URI Validate-Job>
        AuthType Default
        Order deny,allow

```
`</Limit>
  <Limit Send-Document Send-URI Hold-Job Release-Job Restart-Job Purge-Jobs Set-Job-Attributes Create-Job-Subscription Renew-Subscription Cancel-Subscription Get-Notifications $
    AuthType Default
    Require user @OWNER @SYSTEM
    Order deny,allow
    Encryption Required
  </Limit>
  <Limit CUPS-Add-Modify-Printer CUPS-Delete-Printer CUPS-Add-Modify-Class CUPS-Delete-Class CUPS-Set-Default>
    AuthType Default
    Require user @SYSTEM
    Order deny,allow
    Encryption Required
  </Limit>
  <Limit Pause-Printer Resume-Printer Enable-Printer Disable-Printer Pause-Printer-After-Current-Job Hold-New-Jobs Release-Held-New-Jobs Deactivate-Printer Activate-Printer Res$
    AuthType Default
    Require user @SYSTEM
    Order deny,allow
Encryption Required
  </Limit>
  <Limit Cancel-Job CUPS-Authenticate-Job>
    AuthType Default
    Require user @OWNER @SYSTEM
    Order deny,allow
Encryption Required
  </Limit>
  <Limit All>
    Order deny,allow
Encryption Required
  </Limit>

</Policy>
DefaultEncryption Required
ServerCertificate /etc/cups/ssl/server.crt
ServerKey /etc/cups/ssl/server.key

```

Thanks,

**Comment by michaelrsweet** [comment] 2017-10-25 12:39
It would be useful to know what version of CUPS you are using?

This sounds like an issue we recently fixed in the GNU TLS cipher suite support (Issue #5145), which would affect whether certain Windows clients are able to negotiate a secure connection...

**Comment by SiNGhKs** [comment] 2017-10-25 13:11
Thanks,

I am new with cups. The version is CUPS 1.7.5 and i install it on my debian with : 
apt install task-print-server
apt-get install cups

**Comment by michaelrsweet** [comment] 2017-10-25 14:10
OK, well more than likely this has been caused by a GNU TLS update, and the solution will require a change in Debian's CUPS packages (the fix is already in 2.2.x.)

**Closed by michaelrsweet** 2017-10-25 14:10 UTC

**Comment by SiNGhKs** [comment] 2017-10-26 15:29
Hello,
@michaelrsweet
So now i install cups 2.2.5 on Ubuntu Server. With this tutorials :
https://opensource.apple.com/source/cups/cups-69/doc/fr/sam.html#CLIENT_AUTO

I have same error.
`[Client 34] Unable to encrypt connection: An unexpected TLS packet was received.` when i do my lpr

Help please

Cordialy,

**Comment by SiNGhKs** [comment] 2017-10-26 15:30
Hello,
@michaelrsweet
So now i install cups 2.2.5 on Ubuntu Server. With this tutorials :
https://opensource.apple.com/source/cups/cups-69/doc/fr/sam.html#CLIENT_AUTO

I have same error.
[Client 34] Unable to encrypt connection: An unexpected TLS packet was received. when i do my lpr

Help please

Cordialy,

**Comment by prahlad141992** [comment] 2020-04-26 16:50
Hi All,
I have installed recently printer in SuSE 15 SP1. i also  getting same error. Please suggest 

D [26/Apr/2020:11:22:23 -0500] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
D [26/Apr/2020:11:22:23 -0500] [Client 2] Server address is "172.25.108.8".
D [26/Apr/2020:11:22:23 -0500] [Client 2] Accepted from 172.25.108.5:61007 (IPv4)
d [26/Apr/2020:11:22:23 -0500] cupsdAddSelect(fd=13, read_cb=0x55e9bf2f9b40, write_cb=(nil), data=0x55e9bf6e6010)
D [26/Apr/2020:11:22:23 -0500] [Client 2] Waiting for request.
d [26/Apr/2020:11:22:23 -0500] cupsdCheckJobs: 0 active jobs, sleeping=0, ac-power=-1, reload=0, curtime=1587918143
d [26/Apr/2020:11:22:23 -0500] select_timeout: JobHistoryUpdate=0
d [26/Apr/2020:11:22:23 -0500] [Client 2] cupsdReadClient: error=0, used=0, state=HTTP_STATE_WAITING, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=0, request=(nil)(), file=-1
d [26/Apr/2020:11:22:23 -0500] [Client 2] Saw first byte 02, auto-negotiating SSL/TLS session.
E [26/Apr/2020:11:22:23 -0500] [Client 2] Unable to encrypt connection: An unexpected TLS packet was received.
D [26/Apr/2020:11:22:23 -0500] [Client 2] Closing connection.
D [26/Apr/2020:11:22:23 -0500] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
d [26/Apr/2020:11:22:23 -0500] cupsdRemoveSelect(fd=13)
d [26/Apr/2020:11:22:23 -0500] cupsdRemoveSelect(fd=-1)
d [26/Apr/2020:11:22:23 -0500] select_timeout: JobHistoryUpdate=0
