### ISSUE TITLE
Remote lpadmin causes endless '[Client X] Read: status=100' in debug logs

### ISSUE THREAD

**Issue by akorobkin** [apple/cups#4901] opened 2016-10-12 22:04 UTC
On Ubuntu, CUPS 2.2.1 gets stuck and quickly fills up logs with the following lines when debug logging is enabled after issuing lpadmin command from a remote client. 

$ CUPS_SERVER=remote-printserver lpadmin -p myprinter -v socket://net-address
Password for akorobkin on remote-printserver?  ********

It fills the logs while waiting for you to enter the password, and stops after you enter it. But if you control+C the password, canceling your command, it never stops. if you try this twice, you'll see two clients in the endless status loop:

```
D [12/Oct/2016:15:00:42 -0700] [Client 31] Read: status=100
D [12/Oct/2016:15:00:42 -0700] [Client 15] Read: status=100
D [12/Oct/2016:15:00:42 -0700] [Client 31] Read: status=100
D [12/Oct/2016:15:00:42 -0700] [Client 15] Read: status=100
D [12/Oct/2016:15:00:42 -0700] [Client 31] Read: status=100
D [12/Oct/2016:15:00:42 -0700] [Client 15] Read: status=100
D [12/Oct/2016:15:00:42 -0700] [Client 31] Read: status=100
```

strace indicates that it reads /etc/group in a loop, and reports about it.

```
21002 gettimeofday({1476308277, 485205}, NULL) = 0
21002 write(5, "D [12/Oct/2016:14:37:57 -0700] ["..., 61) = 61
21002 poll([{fd=11, events=POLLIN}], 1, 0) = 1 ([{fd=11, revents=POLLIN}])
21002 epoll_wait(3, {{EPOLLIN, {u32=3841574272, u64=139817911960960}}}, 16384, 1000) = 1
21002 recvfrom(11, "\255", 1, MSG_PEEK, NULL, NULL) = 1
21002 open("/etc/group", O_RDONLY|O_CLOEXEC) = 21
21002 fstat(21, {st_mode=S_IFREG|0644, st_size=896, ...}) = 0
21002 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f29e354f000
21002 read(21, "root:x:0:root\ndaemon:x:1:\nbin:x:"..., 4096) = 896
21002 close(21)                         = 0
21002 munmap(0x7f29e354f000, 4096)      = 0
21002 gettimeofday({1476308277, 485757}, NULL) = 0
21002 write(5, "D [12/Oct/2016:14:37:57 -0700] ["..., 61) = 61
21002 poll([{fd=11, events=POLLIN}], 1, 0) = 1 ([{fd=11, revents=POLLIN}])
21002 epoll_wait(3, {{EPOLLIN, {u32=3841574272, u64=139817911960960}}}, 16384, 1000) = 1
21002 recvfrom(11, "\255", 1, MSG_PEEK, NULL, NULL) = 1
21002 open("/etc/group", O_RDONLY|O_CLOEXEC) = 21
21002 fstat(21, {st_mode=S_IFREG|0644, st_size=896, ...}) = 0
21002 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f29e354f000
21002 read(21, "root:x:0:root\ndaemon:x:1:\nbin:x:"..., 4096) = 896
21002 close(21)                         = 0
21002 munmap(0x7f29e354f000, 4096)      = 0
21002 gettimeofday({1476308277, 486257}, NULL) = 0
21002 write(5, "D [12/Oct/2016:14:37:57 -0700] ["..., 61) = 61
21002 poll([{fd=11, events=POLLIN}], 1, 0) = 1 ([{fd=11, revents=POLLIN}])
21002 epoll_wait(3, {{EPOLLIN, {u32=3841574272, u64=139817911960960}}}, 16384, 1000) = 1
21002 recvfrom(11, "\255", 1, MSG_PEEK, NULL, NULL) = 1
21002 open("/etc/group", O_RDONLY|O_CLOEXEC) = 21
21002 fstat(21, {st_mode=S_IFREG|0644, st_size=896, ...}) = 0
21002 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f29e354f000
21002 read(21, "root:x:0:root\ndaemon:x:1:\nbin:x:"..., 4096) = 896
21002 close(21)                         = 0
21002 munmap(0x7f29e354f000, 4096)      = 0
```

Apparently it's line 811 in scheduler/client.c

```
 /*
  * Handle new transfers...
  */

  cupsdLogClient(con, CUPSD_LOG_DEBUG, "Read: status=%d", status);
```

Server is idle doing nothing else, and quickly fills up its log limits. 
Local lpadmin doesn't cause this.

**Comment by michaelrsweet** [comment] 2016-10-14 18:57
Can you attach your cupsd.conf file?

Also, are you using any network account mechanisms, e.g., Kerberos, on this system, or are all of the accounts local?

**Comment by akorobkin** [comment] 2016-10-14 19:20
Here is cupsd.conf.

We're using account caching mechanism similar to nscd, it caches ~300.000 accounts in /etc/passwd.cache and ~10.000 groups in /etc/group.cache. /etc/passwd stores root and daemon accounts (~30 lines), /etc/group stores local groups (~20 lines), while *.cache files keep actual user id info. 

[cupsd.conf.txt](https://github.com/apple/cups/files/530300/cupsd.conf.txt)

**Comment by akorobkin** [comment] 2016-11-08 17:43
Actually, the same happens on 2.1.4, I just never noticed it before.

**Comment by michaelrsweet** [comment] 2016-11-09 03:32
Not sure why this is happening; the lpadmin (client) doesn't re-issue requests while the password prompt is shown, and won't open more than one connection...

**Comment by akorobkin** [comment] 2016-11-09 16:13
It's not lpadmin reissuing requests, lpadmin is already killed by that time. It's server doing something strange. 

Steps: 

`CUPS_SERVER=remote_printserver lpadmin -p myprinter -L "New Location"`
`Password for akorobkin on remote_printserver?` **Ctrl+C**

lpadmin is interrupted, remove server is stuck doing "Read: status=100"

**Comment by tomjanowski** [comment] 2016-11-22 18:20
I have the same issue. When I request printing from a Windows 10 client, cupsd is stuck at 100%, whether I print or not. It appears some authorization issue. Strace show continuous /etc/group open and close. At this moment cupsd is unusable for me. The printing succeeds and it is correct, but a program that is idle should not consume all my resources. Is there any way I could help locating the problem? Which part of cupsd can open /etc/group? It does not look like this is done directly, as I do not see any references to /etc/group in the source code.

**Comment by tomjanowski** [comment] 2016-11-28 17:32
It appears imposing any restrictions in sections like:
<Location />
AuthType Basic
Require valid-user
</Location>
or in /Printers location causes cupsd to enter an infinite loop and spin at 100% forever every time any connection to cupsd from a remote site is attempted. With no restrictions, keeping only per-printer authentication results in no issue. This limits my ability to limit the access to the list of printers to authenticated users (ideally I would like to restrict any access to the server to authenticated users).

**Comment by tomjanowski** [comment] 2016-11-28 17:59
In the above I meant the following section:
`<Location />`
`AuthType Basic`
`Require valid-user`
`</Location>`

**Comment by tomjanowski** [comment] 2016-11-28 18:10
I see that **akorobkin** has a similar setup, he requires encryption right for the root `/` location, but he does not require authorization. In my setup I require authorization that implies encryption. Removing restrictions for `/` removes the problem with cupsd entering 100% CPU loop.

**Comment by akorobkin** [comment] 2016-11-28 20:03
Tomasz, thanks for troubleshooting this deeper. Just out of curiosity, does your auth system have thousands of users?

**Comment by tomjanowski** [comment] 2016-11-29 16:08
I do use an external kerberos authentication using PAM as a proxy. But I tried to make one user local on the server and test remote printing using this username, with the same result (in that case cupsd used PAM too, but PAM did not query external sources). The print server itself will be deployed for a small group of about 30 people, while the external kerberos has around 50,000 users.

I think that what happens here is that while encrypted channel was tested for the "standard" configuration, it was not fully tested in the configuration I attempted (where any kind of access to the print server will have to be encrypted and authorized). I think CUPS cannot close a connection or it gets confused about the status of a connection that was closed by the remote side and looks open on the server side. That would explain this infinite loop it is entering. Accessing /etc/group looks to me like a side effect. I will look into this later if I have time, but I would look for a loop that accesses user information and checks status of an active network connection in the same iteration, a loop that is exited only if the network connection is closed (and this remote closure is not properly detected).

I am slightly surprised why this issue has low priority.

**Comment by tomjanowski** [comment] 2016-11-30 19:42
Please see also #4929

**Comment by michaelrsweet** [comment] 2017-01-04 22:21
@tomjanowski The priority reflects that a) I have yet to be able to reproduce this on any of my systems or VMs (and I have been trying, believe me!) and b) we have exactly two reports of this problem (where I would expect something like this to cause widespread chaos...)

**Comment by tomjanowski** [comment] 2017-01-05 00:32
@michaelrsweet: (a) Could it be that only the Debian version has this problem? (b) it might be that not too many people use encryption and PAM authentication in CUPS. Most installations I have seen do not use encryption at all. They just restrict CUPS usage to local networks. On my system the problem is almost guaranteed to happen after every remote client connection.

**Comment by michaelrsweet** [comment] 2017-01-05 02:58
@tomjanowski I've been testing with Ubuntu, and PAM + encryption is universally used on all UNIX/Linux platforms supported by CUPS (even macOS!)

The default since CUPS 1.2 has been to encrypt the connection as soon as authentication is required - you have to explicitly disable it.

**Comment by tomjanowski** [comment] 2017-01-05 03:04
@michaelrsweet Yes, but the print servers I have seen so far do not use authentication. Anyways, please let me know how I can help debugging this problem.

**Comment by michaelrsweet** [comment] 2017-01-05 16:18
AHAH! I was able to get this to happen in a fresh Ubuntu VM, although I am still not certain why we are in this state to begin with... Have things open in gdb now and investigating.

**Comment by michaelrsweet** [comment] 2017-01-05 16:46
[master a2f30a7] Force HTTP state when sending a response (possible fix for Issue #4901)

Try this change; so far no side-effects I can see, and it fixes the continuous stream of (bogus) read callbacks (the scheduler doesn't think the connection has been closed...)

**Comment by akorobkin** [comment] 2017-01-05 19:25
Looks like the change resolves the problem, thank you.

**Comment by tomjanowski** [comment] 2017-01-06 20:06
It appears that the issue with infinite loop is resolved, but for some reason I have troubles with Windows clients if my setup requires authorization at the topmost level (case (a) in issue #4929 ). Now I am not sure why I reported that cups could print from Windows if Location / required "valid-user", but somehow svchost either enters infinite loop (Windows 7) or Windows 10 just reports it cannot print to the printer. Occasionally it can print, but most of the time it cannot. I could post my configuration files if this were of any help.

**Comment by tomjanowski** [comment] 2017-01-06 20:51
Is the only change needed contained in a2f30a7? It contains 3 lines of code. I applied this as a patch to whatever sources I already had in Debian source package.

I still see 100% cpu in cupsd and Windows 7 as a client. I am not sure whether this is new or not, but Windows 7 has its svchost entering infinite loop too. Shutting down Windows client does not stop cupsd from running at 100% CPU. The only change I have noticed is that now I can print using lp for case (1) in issue #4929, could it be that something was added via Debian updates in the meantime (?). <Location /> requiring a valid user seems to suffer the same problems. Without the patch Windows 7 forces cupsd to run at 100% cpu, but its svchost does not spin at 100%. I like my cupsd without the patch more, since the patch added troubles to Windows 7 clients, while the behavior of the server is similar (infinite loop).

Windows 10 does not put cupsd at 100% CPU with the patch applied, but it refuses to print most of the time. Sometimes it prints. It complains  that there is connectivity problem with the server. Without the patch Windows 10 prints with no problems, only cupsd runs at 100% after the first print.

This is my empirical data I have gathered so far.

**Comment by tomjanowski** [comment] 2017-01-06 21:20
One correction: the info about svchost spinning at 100% due to printing is unreliable. Now I see that it could be Windows Update (I run my Windows clients from VM and since I do not run them often they are busy updating their "Windows Update" databases).

**Comment by michaelrsweet** [comment] 2017-01-13 22:31
@tomjanowski Can you file a separate issue for your Windows printing issues? Historically Windows has had problems with authenticated IPP print queues in general, so it could be with the fix you are just getting past the initial connection issues and hitting another one...

Closing this issue since the main reported problem is fixed.

**Closed by michaelrsweet** 2017-01-13 22:31 UTC
Labels: P2 - Low

**Comment by mbechler** [comment] 2017-04-16 13:25
Maybe I can shed some light on that. Before finding this report (after being unable to reproduce my 2.1.4 findings against master) I spent a fair amount of time debugging a similar one, that I have been hitting pretty regularly in a production environment, which I would very much expect to be related:

1. Establish a TLS connection
2. Make a POST/PUT request
3. Server initiates connection shutdown (e.g. when an auth/access error is returned, but probably also on other occasions)
4. For TLS this leaves the connection (half) open and keeps the read callback (not absolutely sure why?)
5. Client send's some extra garbage data (I would guess that even a proper close_notify response could be enough there, and I have actually seen this happen pretty regularly in a production environment with cups clients), before the read handler for that connection is active again (maybe even race against the shutdown() call, or that just doesn't do what one would expect from it, maybe this is linux/epoll specific)
5. We end up in a state where we are still in HTTP_STATE_POST_RECV, data_remaining=0 but there is still data available on the file descriptor making the EOF checks fail (PEEK returns available). httpRead however always returns 0 without reading the data -> read event triggers again and again, tight loop that never ends (activity is set by the call to read so no timeouts either).

So in conslusion that can happen (at least on linux/epoll?) for every server initiated close on a TLS connection.

I managed to build a pretty reliable reproducer, which I'd be happy to share (maybe better in private as this also is a nice DOS vector) and can also provide some additional debugging info if you like.

Regarding the fix, I seems that it does indeed fix the issue in the described scenario and also in the one I have seen (by fully closing the connection on the next read handler call through it's invalid state), but I would say that there is a more general issue with the partial closing logic for TLS connections, there may be other occasions where it can be triggered.

**Comment by akorobkin** [comment] 2017-04-18 16:33
Thanks for this very detailed diagnostics, I wonder if this is the same issue that I'm experiencing in https://github.com/apple/cups/issues/4586 
There, CUPS stops properly handling incoming connections after a certain number of open TLS connections. The symptoms look very similar to what is described here.
