### ISSUE TITLE
cupsGetDests's behaviour is difference between CUPS2.2.10 & CUPS2.2.12

### ISSUE THREAD

**Issue by tangyanli** [apple/cups#5683] opened 2019-11-13 09:21 UTC
Assume the default printer name is set as below:
/etc/cups/printers.conf: PrinterA
~/.cups/lpoptions: PrinterB

When use the cupsGetDests to get the default printer name:
Ubuntu19.04 (CUPS2.2.10): The PrinterB's dest->is_default = 1
Ubuntu19.10 (CUPS2.2.12): The PrinterA's dest->is_default = 1

I tried to analyze the code, is the cups_enum_dests()'s logic changed?
(1) data.def_name stores the system default name ("PrinterA")
(2) Get the use default name from ~/.cups/lpoptions ("PrinterB")
(3) According the data.def_name ("PrinterA") to set the dest->is_default = 1

[getDefaultPrinter.txt](https://github.com/apple/cups/files/3840325/getDefaultPrinter.txt)

**Comment by michaelweghorn** [comment] 2019-11-14 06:53
I didn't test yet, but does merge request #5679 make a difference?

**Comment by tangyanli** [comment] 2019-11-14 08:59
CUPS2.2.12 was released at Aug 15. It seems not the #5679 causes the problem.

**Comment by michaelweghorn** [comment] 2019-11-14 09:08
> CUPS2.2.12 was released at Aug 15. It seems not the #5679 causes the problem.

You're right, #5679 is not even included in any CUPS release, not even in the development version in git. What I meant was that it might possibly fix the issue, since what you describe sounds similar to #5681, and #5679 seemed to fix that one for me in a quick test.

However, I only tested with git master (i.e. CUPS 2.3.X), so your issue might be a different one.

**Comment by tangyanli** [comment] 2019-11-14 09:17
I also found another phenomenon as below:
========
Assume the default printer name is set as below:
/etc/cups/printers.conf: PrinterA
~/.cups/lpoptions: PrinterB

When use lpoptions to set PrinterC's setting:
lpoptions -p PrinterC -o PageSize=A4
↑
The default printer name recorded in the ~/.cups/lpoptions becomes "PrinterA"

========

And I tried to fix the cups_enum_dests(), the above phenomenon disappears.
Because I am not familiar with CUPS coding, is the fix OK?

[dest.txt](https://github.com/apple/cups/files/3845597/dest.txt)

**Comment by tangyanli** [comment] 2019-11-14 09:19
I also found another phenomenon as below:
===
Assume the default printer name is set as below:
/etc/cups/printers.conf: PrinterA
~/.cups/lpoptions: PrinterB
When use lpoptions to set PrinterC's setting:
lpoptions -p PrinterC -o PageSize=A4
↑
The default printer name recorded in the ~/.cups/lpoptions becomes "PrinterA"
===
And I tried to fix the cups_enum_dests(), the above phenomenon disappears.
Because I am not familiar with CUPS coding, is the fix OK?

[dest.txt](https://github.com/apple/cups/files/3845605/dest.txt)

**Comment by tangyanli** [comment] 2019-11-14 09:20
I also found another phenomenon as below:

Assume the default printer name is set as below:
/etc/cups/printers.conf: PrinterA
~/.cups/lpoptions: PrinterB
When use lpoptions to set PrinterC's setting:
lpoptions -p PrinterC -o PageSize=A4
↑
The default printer name recorded in the ~/.cups/lpoptions becomes "PrinterA"

And I tried to fix the cups_enum_dests(), the above phenomenon disappears.
Because I am not familiar with CUPS coding, is the fix OK?

[dest.txt](https://github.com/apple/cups/files/3845609/dest.txt)

**Comment by michaelweghorn** [comment] 2019-11-14 09:25
> And I tried to fix the cups_enum_dests(), the above phenomenon disappears.
> Because I am not familiar with CUPS coding, is the fix OK?
> 
> [dest.txt](https://github.com/apple/cups/files/3845609/dest.txt)

Is "dest.txt" your modified version that contains the fix? I'm not really familiar with CUPS coding either, but I think that creating a pull request would be a better way to suggest a fix, in particular since other places in the file might change in the meantime, making it hard to see what your actual change was by just looking at the attachment.

**Comment by tangyanli** [comment] 2019-11-14 09:30
It is OK.
I then will test the newest code from the git to check whether the issue still exists or not.
If still exists, I will pull a request.

BTW: the dest.txt (actually dest.c) is changed based on the CUPS2.2.12 release coding.  :-)

**Comment by michaelrsweet** [comment] 2019-11-14 19:22
OK, this is a dupe of Issue #5681 - fixes have been pushed to the master and 2.2.x branches.

**Closed by michaelrsweet** 2019-11-14 19:22 UTC

**Comment by tangyanli** [comment] 2019-11-15 01:12
I am sorry, I have tested the branch CUPS2.3.x and CUPS2.2x, this issue is not fixed entirely.
