### ISSUE TITLE
CUPS filled my drive with giant error_log file

### ISSUE THREAD

**Issue by pauljurczak** [apple/cups#5804] opened 2020-07-08 14:46 UTC
CUPS stopped working on my Ubuntu 18.04 due to my tinkering with file permissions in /usr/lib folder. My fault. Unfortunately, in less than 24 hours, it produced 0.25TB of error log files with text like this:
```
E [21/Jun/2020:14:13:06 -0600] File \"/usr/lib/cups/notifier/dbus\" has insecure permissions (0100775/uid=0/gid=0).
W [21/Jun/2020:14:13:06 -0600] Notifier for subscription 88 (dbus://) went away, retrying!
```
Does this message have to be repeated millions of times?

**Comment by jschwender** [comment] 2020-07-08 20:43
this file needs 755 permissions, owner root. 
You may stop logging by editing /etc/cupsd.conf: LogLevel none 
Or, using rsyslog y ou may lookin for the $RepeatedMsgReduction config switch, which turns such duplicate messages into one by logging "Last line repeated n times". You can also discard unwanted messages.

**Comment by pauljurczak** [comment] 2020-07-08 23:00
Perhaps having a default with threshold for maximum number of times the same message is logged consecutively would solve the problem. Logging, which kills the system by filling the storage is not a user-friendly design. Also checking the file permission in such quick succession seems to be pointless: after the first failure, increase the wait between checks and keep increasing, if it fails again.

**Comment by jschwender** [comment] 2020-07-23 08:11
looks like a duplicate of #5790

**Comment by michaelrsweet** [comment] 2021-03-12 15:19
Default MaxLogSize is 1m. Ubuntu changes it...

**Closed by michaelrsweet** 2021-03-12 15:19 UTC
