### ISSUE TITLE
cupsd crash - malloc; pointer being freed was not allocated

### ISSUE THREAD

**Issue by markknopper** [apple/cups#5871] opened 2020-12-20 05:46 UTC
I am getting the same crash mentioned in this issue (URL below), with the latest macOS Big Sur 11.2 Beta (20D5029f). Cupsd crashes about 50% of the time when printing to a Samsung C430W printer over Airprint. When the crash happens the job doesn't print but it gets removed from the print queue.
[cupsd_2020-12-18-215446_bulbous10.crash.zip](https://github.com/apple/cups/files/5720590/cupsd_2020-12-18-215446_bulbous10.crash.zip)

https://github.com/apple/cups/issues/5554

**Comment by markknopper** [comment] 2020-12-20 16:58
Before it crashes, I see these logs in /var/log/cups/access_log:

localhost - - [20/Dec/2020:11:45:10 -0500] "POST /printers/Samsung_C43x_Series__SEC30CDA7BA70CB_ HTTP/1.1" 200 453 Print-Job successful-ok
localhost - - [20/Dec/2020:11:56:38 -0500] "POST /printers/Samsung_C43x_Series__SEC30CDA7BA70CB_ HTTP/1.1" 200 4315 Create-Job successful-ok
localhost - - [20/Dec/2020:11:56:38 -0500] "POST /printers/Samsung_C43x_Series__SEC30CDA7BA70CB_ HTTP/1.1" 200 69798 Send-Document successful-ok
localhost - - [20/Dec/2020:11:56:38 -0500] "POST / HTTP/1.1" 200 344 Set-Job-Attributes successful-ok
localhost - - [20/Dec/2020:11:56:41 -0500] "POST / HTTP/1.1" 200 69638 CUPS-Get-Document successful-ok

**Comment by markknopper** [comment] 2020-12-20 17:17
Got it to crash again, this time with debug logging on. 
[error_log.txt.zip](https://github.com/apple/cups/files/5721244/error_log.txt.zip)

**Comment by markknopper** [comment] 2020-12-20 17:30
Config info from MacOS System Information app:

Samsung C43x Series (SEC30CDA7BA70CB):

  Status:	Idle
  Print Server:	Local
  Driver Version:	2.0
  Default:	Yes
  System Printer Sharing:	No
  Shared:	No
  URI:	dnssd://Samsung%20C43x%20Series%20(SEC30CDA7BA70CB)._ipp._tcp.local./?uuid=16a65700-007c-1000-bb49-30cda7ba70cb
  PPD:	Samsung C43x Series-AirPrint
  PPD File Version:	2.0
  PostScript Version:	(3010.000) 0
  CUPS Version:	2.3.4 (cups-494.1)
  Scanning support:	No
  Printer Commands:	none 
  AirPrint Version:	1.4
  URF Version:	1.4
  Printer Firmware Version:	IPP:1.0,1.1,2.0,URF:1.4
  Added:	Tuesday, June 9, 2020 at 12:52:00 PM Eastern Daylight Time
  CUPS filters:
  image/urf:	processed in printer
  Fax support:	No
  PDEs:

**Comment by michaelrsweet** [comment] 2021-03-11 13:50
Pretty sure I know the cause, investigating...

**Comment by michaelrsweet** [comment] 2021-03-11 19:47
Dupe of #5895 (or at least that's the one I'll use for the lead bug).

**Closed by michaelrsweet** 2021-03-11 19:47 UTC
Labels: P5 - Critical
