### ISSUE TITLE
_cupsConnect does not reuse domain socket connections

### ISSUE THREAD

**Issue by svarshavchik** [apple/cups#5239] opened 2018-01-26 12:00 UTC
Referencing https://www.cups.org/doc/cupspm.html#submitting-a-print-job

The last code sample there does not work as is. The current code in cupsFinishDestDocument() does not correctly handle a connection that's specified as CUPS_HTTP_DEFAULT.

Quoting https://lists.cups.org/pipermail/cups-devel/2018-January/017113.html

Calling cupsFinishDestDocument(), as shown in the sample code, results in _cupsConnect(), which blows away the existing connection and creates a new one, as follows:

998         if (strcmp(cg->http->hostname, cg->server) ||
(gdb)
999             cg->ipp_port != httpAddrPort(cg->http->hostaddr) ||
(gdb)
998         if (strcmp(cg->http->hostname, cg->server) ||
(gdb)
1031            httpClose(cg->http);
(gdb) p cg->http->hostaddr
$1 = (http_addr_t *) 0x9c2dd8
(gdb) p *cg->http->hostaddr
$2 = {addr = {sa_family = 1, sa_data = "/var/run/cups/"}, ipv4 = {
    sin_family = 1, sin_port = 30255, sin_addr = {s_addr = 1915712097},
    sin_zero = "un/cups/"}, ipv6 = {sin6_family = 1, sin6_port = 30255,
    sin6_flowinfo = 1915712097, sin6_addr = {__in6_u = {
        __u6_addr8 = "un/cups/cups.soc", __u6_addr16 = {28277, 25391, 28789,
          12147, 30051, 29552, 29486, 25455}, __u6_addr32 = {1664052853,
          796094581, 1936749923, 1668248366}}}, sin6_scope_id = 107}, un = {
    sun_family = 1,
    sun_path = "/var/run/cups/cups.sock", '\000' <repeats 84 times>},
  pad = "\001\000/var/run/cups/cups.sock", '\000' <repeats 230 times>}
(gdb) p htons(30255)
$3 = 12150
(gdb) p cg->ipp_port
$4 = 631
(gdb) where
#0  _cupsConnect () at request.c:1031
#1  0x00007ffff6cec0d6 in cupsFinishDestDocument (http=<optimized out>,
    dest=0x965070, info=0x99c230) at dest-job.c:273

Letting it continue on this code path eventually results in an IPP_STATUS_ERROR_INTERNAL.

**Comment by michaelrsweet** [comment] 2018-01-29 19:24
This looks more like an issue with _cupsConnect not reusing domain socket connections. Investigating...

**Comment by svarshavchik** [comment] 2018-01-30 00:24
Based on my read of _cupsConnect logic it reuses the existing connection provided all of its parameters match: same expected destination host, and same port.

Except that when POSTing a new job, that goes over a connection to a destination port other than port 631, based on what I dumped with gdb.

**Comment by svarshavchik** [comment] 2018-01-30 00:25
clicked on the wrong button, sorry...

**Comment by michaelrsweet** [comment] 2018-02-01 02:04
Doing more investigation, this appears to be a dupe of Issue #5098 which was fixed in CUPS 2.2.5 - it looks like (based on your mailing list post) that you are using 2.2.4. Either upgrade to get the fix or use your own HTTP connection.

**Closed by michaelrsweet** 2018-02-01 02:04 UTC
Labels: P4 - High
