### ISSUE TITLE
cupsd crashed with SIGSEGV in avahi_entry_group_free()

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5268] opened 2018-03-16 17:15 UTC
I got following bug report by an Ubuntu user:
https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1725749
CUPS crashed immediately after starting LUbuntu 17.10.
The report contains all needed information, especially stack traces:
https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1725749/+attachment/4982979/+files/ThreadStacktrace.txt
The problem occurred on the upcoming Ubuntu 17.10 with CUPS 2.2.2.
This bug has happened with an older CUPS version and can perhaps already be solved in the current version (2.2.6/2.3.x).

**Comment by tillkamppeter** [comment] 2018-03-16 17:17
Other users found this bug also in CUPS 2.2.4 and 2.2.6 (duplicate list in the Ubuntu bug report).

**Comment by michaelrsweet** [comment] 2018-03-17 00:19
This appears to be the same problem you reported in issue #5128.

"*srv" is checked prior to the call to avahi_entry_group_free, so it isn't clear how this is happening - no other threads are around to change it, so I guess I'll need to check the generated assembly code to make sure we are not running into a compiler bug.

**Comment by michaelrsweet** [comment] 2018-03-19 17:57
OK, so the assembly shows GCC optimizing the NULL check out, but probably because we also check it at the start of the function (so the NULL check inside the HAVE_AVAHI is unnecessary).

I will continue looking at what might be causing this - something is changing the value of the srv-pointed variable in parallel, leading to the crash.

**Comment by michaelrsweet** [comment] 2018-03-19 23:52
@tillkamppeter Can you attach a copy of the patched dirsvc.c source file for the original bug report? The line numbers don't appear to match up with the official CUPS 2.2.4 version of dirsvc.c which is making it hard for me to trace out the crash, and I am currently unable to reproduce with the stock sources on Ubuntu 17.10.

**Comment by tillkamppeter** [comment] 2018-03-20 13:21
Here is the patched version of Ubuntu 2.2.6 (Bionic, 18.04):

[dirsvc.c.txt](https://github.com/apple/cups/files/1829443/dirsvc.c.txt)

**Comment by tillkamppeter** [comment] 2018-03-20 13:26
Here is the patched version of CUPS 2.2.4 (Artful, 17.10):

[dirsvc.c.txt](https://github.com/apple/cups/files/1829464/dirsvc.c.txt)

**Comment by michaelrsweet** [comment] 2018-03-21 21:56
OK, still makes no sense, will try pushing a slightly different change for you to try.

**Comment by michaelrsweet** [comment] 2018-03-21 22:00
[master 561e0647a] Try another fix for Avahi crash (Issue #5268)

[master d0bfbc98b] Try another fix for Avahi crash (Issue #5268)

[branch-2.2 9d72065fa] Try another fix for Avahi crash (Issue #5268)

**Comment by michaelrsweet** [comment] 2018-03-21 22:01
(two commits for master because I forgot to move the "*srv=NULL" code inside the lock.

**Comment by tillkamppeter** [comment] 2018-03-22 10:29
Thank you for the quick fix.
The reporting users did not get the crash regularly, but most probably only once, but as if a crash under Ubuntu occurs, the crash reporting system is triggered automatically, they have reported the bugs. So offering a package version to them with your patch applied will most probably not lead to a reliable answer.
So the best thing I can do is to apply the patch to the current Ubuntu package (or upgrade it to 2.2.7, when will you release it?) and see whether bug reports of this kind will disappear.

**Comment by michaelrsweet** [comment] 2018-03-22 12:39
OK, I'll close this issue as fixed then - feel free to file a new one if the problem continues to be reported after the update.

**Closed by michaelrsweet** 2018-03-22 12:39 UTC
Labels: P3 - Moderate, Waiting on Review

**Comment by OneEyedMonk** [comment] 2018-03-27 13:44
Its still there. 16.04 LTS fresh install +15 days of updates.

**Comment by michaelrsweet** [comment] 2018-03-27 14:38
@OneEyedMonk I don't know whether Till has updated the Ubuntu packages.

**Comment by tillkamppeter** [comment] 2018-03-27 16:56
I did not add the patches for all the crash bugs I forwarded upstream to Ubuntu one by one but was waiting for CUPS 2.2.7 containing all fixes. It was released today so soon this bug's fix will make it into Ubuntu.
