### ISSUE TITLE
authentication problems with web interface

### ISSUE THREAD

**Issue by Rakuman279** [apple/cups#5628] opened 2019-08-05 14:09 UTC
cups 2.2.11 on openbsd 6.5
first attempt to add a printer presented with a dialog box that would not accept either my name or root with passwords, kept just throwing up the box again, so I reset authentication to none, attempting to add a printer nothing happens, it just looks like it cant find anything but I know from using it on other systems it should ofer me to enter where the printer is, though find new printers and manage printers show no printers, attempting to view the logs via the interface wants a user name and passwd but does not present anywhere to enter it.
The only change to the conf file is to alter authentication to none.
access log just repeats
localhost - - [05/Aug/2019:15:01:16 +0100] "POST / HTTP/1.1 401 75 CUPS-Get-Devices successful-ok  many times

nothing in error_log
nothing in messages

any suggestions appreciated, thanks, I am trying to add a networked printer

**Comment by michaelrsweet** [comment] 2019-08-05 23:02
Try enabling debug logging (cupsctl --debug-logging) - I suspect an issue with the PAM configuration.

**Comment by wgnann** [comment] 2019-11-07 18:32
Hello,

I got the same problem with either CUPS 2.2.10 or CUPS 2.3.0.

My setup was Debian's default plus AuthType Negotiate. Kerberos is working properly since I use it to access the CUPS server's via web using AuthType Negotiate inside <Location /> scope.
`DefaultAuthType Negotiate
<Location />
  AuthType Default
  Order allow,deny
  Allow @LOCAL
</Location>`

But if I try to add a printer (I think it is the CUPS-Add-Modify-Printer operation), the browser just keeps loading forever.
`<Limit CUPS-Add-Modify-Printer CUPS-Delete-Printer CUPS-Add-Modify-Class CUPS-Delete-Class CUPS-Set-Default>
  AuthType Default
  Order deny,allow
</Limit>`,

The log was flooded with [Client %d] entries just like the following:
D [07/Nov/2019:17:48:27 +0000] [Client 27727] Server address is "/run/cups/cups.sock".
D [07/Nov/2019:17:48:27 +0000] [Client 27727] Accepted from localhost (Domain)
D [07/Nov/2019:17:48:27 +0000] [Client 27727] Waiting for request.
D [07/Nov/2019:17:48:27 +0000] [Client 27727] POST / HTTP/1.1
D [07/Nov/2019:17:48:27 +0000] [Client 27727] Read: status=200, state=6
D [07/Nov/2019:17:48:27 +0000] [Client 27727] No authentication data provided.
D [07/Nov/2019:17:48:27 +0000] [Client 27727] cupsdSendHeader: code=401, type="text/html", auth_type=0
D [07/Nov/2019:17:48:27 +0000] [Client 27727] WWW-Authenticate: PeerCred
D [07/Nov/2019:17:48:27 +0000] [Client 27727] Closing connection.

`grep authentication error_log  -c

**Comment by michaelrsweet** [comment] 2019-12-04 16:47
This is a dupe of #5596...

**Closed by michaelrsweet** 2019-12-04 16:47 UTC
Labels: Cannot Reproduce
